dist: xenial


language: python

addons:
  apt:
    packages:
      - libenchant-dev
      - texlive-latex-recommended
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - latexmk

install:
  - pip install -r requirements.txt # install the required packages

script:
  - cd docs
  - make html
  - make latexpdf
  - make install
  - cd ..
  - mkdir _build
  - mv docs/_build/html _build/.

# Ask Travis CI to copy the documentation to the gh-pages branch of your GitHub repository

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $travis-token
  keep-history: true
  on: 
     branch: master
  local_dir: _build/html
