name: Documentation Bug Report
description: File an Arcana Network documentation bug report
title: "[DocsBug]: "
labels: ["docs", "bug", "triage"]
assignees:
  - shaloo
body:
  - type: markdown
    attributes:
      value: |
                :wave:  Hey, there!
        
        Thank you for using [Arcana Network Repo Name. For e.g. Storage, Auth, Demo-App etc.]
        
        Help us timely address and prioritize your issue by going through this checklist and providing all the requisite issue details.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
