name: Documentation Bug Report
description: File an Arcana Network documentation bug report
title: "[DocsBug]: "
labels: ["docs", "bug", "triage"]
assignees:
  - shaloo
body:
  - type: markdown
    attributes:
      value: |
      
        :wave:  Hey, there!
        *Thank you for using [Arcana Network Repo Name. For e.g. Storage, Auth, Demo-App etc.]*
        Help us timely address and prioritize your issue by going through this checklist and providing all the requisite issue details.
  - type: checkboxes
    id: issue-checklist
    attributes:
      label: Issue Checklist
      description: Before you submit the issue, verify it is indeed a bug and not a question.
      options:
        - label: Is this something you can **debug and fix**? Send a pull request! Your contributions are valuable to us.
          required: false
        - label: Have a **usage question**? Ask your question on [StackOverflow](https://stackoverflow.com/search?q=%22arcana+network%22%2B%22XAR%22) or [Discord channel](https://discord.com/invite/w6ej4FtqYS). We use GitHub solely for bugs and feature enhancement requests.
          required: false
        - label: Is this a support query related to your specific use case? Contact us at [support@arcana.network](mailto:support@arcana.network).
          required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information about your bug?
      placeholder: ex. youremail@youremailprovider.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Create GitHub Issue"
  - type: markdown
    attributes:
      value: |
      
        Make sure to add all the information needed to understand the bug or your feature request. 
        
        If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the scenario and the bug.
      placeholder: Tell us what you see!
      value: "Something did not work when you tried..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us, what did you expect to happen?
      placeholder: Tell us about the expected behavior!
      value: "This error should show up or this value should be returned, etc."
    validations:
      required: true
